### ISSUE TITLE
TypeError: data.trim is not a function

### ISSUE THREAD

**Issue by lazytyper** [bradstewart/electron-boilerplate-vue#27] opened 2016-06-05 20:01 UTC
Actually, I've updated node to v6.2.1. I'm not sure if this is the reason, but I'm getting this error when I try `npm start`:

```
TypeError: data.trim is not a function
    at format (/home/egon/dev/electron-vue/build/dev-runner.js:16:10)
    at Socket.<anonymous> (/home/egon/dev/electron-vue/build/dev-runner.js:30:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)
```

With this quickfix in `build/dev-runner.js` I got it to work:

``` javascript
function format (command, data, color) {
  // data seems to be a buffer and not a string
  if (typeof data !== 'string') {
    data = data.toString();
  }
  return color + command + END +
    '  ' + // Two space offset
    data.trim().replace(/\n/g, '\n' + repeat(' ', command.length + 2)) +
    '\n'
}
```

**Comment by davejm** [comment] 2016-06-06 17:15
Had same problem. @eschmid72's solution worked for me.

**Comment by djekl** [comment] 2016-06-23 08:16
Yeah, this only seems to be an issue on Windows. But the fix looks to have worked also

**Comment by davejm** [comment] 2016-06-23 08:20
I am using Linux

**Comment by djekl** [comment] 2016-06-23 08:21
Ahh ok, I apologise. I assumed that Linux would work with it working fine for me in OSX, and only having this issue on Windows.

**Comment by davejm** [comment] 2016-06-23 08:22
My comment went. Original comment was "I am on Linix".

**Comment by davejm** [comment] 2016-06-23 08:23
Hmm weird

**Comment by djekl** [comment] 2016-06-23 08:24
What version of Node and NPM do you have?

Here is mine

``` bash
 ✝ ~  node -v
v5.11.1
 ✝ ~  npm -v
3.5.2
```

**Comment by davejm** [comment] 2016-06-23 08:26
I'm at work atm so can't give exact versions but I know I have Node V6 and NPM V3. Pretty sure the problem occurs at Node V6

**Comment by djekl** [comment] 2016-06-23 08:28
Ahh, ok. Let me check my version on Windows. I know that many things have problems in Node v6, thats why I run v5 on all my systems.

**Comment by djekl** [comment] 2016-06-23 08:28
Yeah, v6 on Windows. Will install v5 now, and revert the change I made. See if I still have the same issue.

Edit:
Looking at the site, v4 is LTS and v6 is the latest. So could be that. We will see...

**Comment by djekl** [comment] 2016-06-23 11:21
Just to confirm, this looks to be an issue with Node v6. Should merge OK as works fine in Node v4 - v5

**Comment by seegwen** [comment] 2016-07-06 13:16
I can confirm this bug.

el capitan 10.11.5 fresh install

```
$ node -v
v6.2.2
$ npm -v
3.9.5
```

@eschmid72's change did indeed fix the issue.

**Comment by bradstewart** [comment] 2016-07-23 05:57
Merged https://github.com/bradstewart/electron-boilerplate-vue/pull/33 which resolves this issue.

**Closed as completed by bradstewart** 2016-07-23 05:57 UTC
